language: python

python:
    # not used directly, but this sets TRAVIS_PYTHON_VERSION so we can use it
    # in anaconda as well (we don't support python less than 3.5)
    - 3.5
    - 3.6

os:
    - linux
    # - osx   # currently osx python projects are not supported in Travis

before_install:

    # Use utf8 encoding. Should be default, but this is insurance
    # against future changes

    - export PYTHONIOENCODING=UTF8

    # Install miniconda following instructions at
    # http://conda.pydata.org/docs/travis.html
    
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda  # get latest conda version
    # Useful for debugging any issues with conda
    - conda info -a

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:

    - conda create --name cta-dev python=$TRAVIS_PYTHON_VERSION
    - conda env update -n cta-dev --quiet --file environment.yml
    - source activate cta-dev
    - ulimit -s 16000  # increase stack size limit, for libhessio
    - pip install travis-sphinx
    - python setup.py install


script:
    - make test
    - ctapipe-info --version # print out the version string
    - travis-sphinx --nowarn --source=docs/ build

after_script:
    - source deactivate

after_success:
    - travis-sphinx deploy

  

